### ISSUE TITLE
7 errors

### ISSUE THREAD

**Issue by PyMaster22** [en-GB/3-manifold#1]
when I compile using clang on Linux (obviously otherwise there wouldn't be problems) after resolving the basic "file not found" errors it gave me 7 errors all complaining about function definitions.
The full error (as HTML):
<pre><b>3_less.c:170:43: </b><font color="#EF2929"><b>error: </b></font><b>function definition is not allowed here</b>
fn char *shader_error_log(unsigned shader) {
<font color="#8AE234"><b>                                          ^</b></font>
<b>3_less.c:180:45: </b><font color="#EF2929"><b>error: </b></font><b>function definition is not allowed here</b>
fn char *program_error_log(unsigned program) {
<font color="#8AE234"><b>                                            ^</b></font>
<b>3_less.c:190:65: </b><font color="#EF2929"><b>error: </b></font><b>function definition is not allowed here</b>
fn unsigned create_shader(unsigned prog, GLenum type, char *src){
<font color="#8AE234"><b>                                                                ^</b></font>
<b>3_less.c:205:59: </b><font color="#EF2929"><b>error: </b></font><b>function definition is not allowed here</b>
fn unsigned create_program(char *vert_src, char *frag_src) {
<font color="#8AE234"><b>                                                          ^</b></font>
<b>3_less.c:228:33: </b><font color="#EF2929"><b>error: </b></font><b>function definition is not allowed here</b>
fn void loop(GLFWwindow *window) {
<font color="#8AE234"><b>                                ^</b></font>
<b>3_less.c:550:33: </b><font color="#EF2929"><b>error: </b></font><b>function definition is not allowed here</b>
int main(int argc, char *args[]) {
<font color="#8AE234"><b>                                ^</b></font>
<b>3_less.c:578:2: </b><font color="#EF2929"><b>error: </b></font><b>expected &apos;}&apos;</b>
}
<font color="#8AE234"><b> ^</b></font>
<b>./3_roomgen_output.h:5339:69: </b><font color="#555753"><b>note: </b></font>to match this &apos;{&apos;
fn View room27_update(View v, Room **r, float w, float d, float dt) {
<font color="#8AE234"><b>                                                                    ^</b></font>
7 errors generated.</pre>

**Comment by en-GB** [comment]
sounds like for some reason the last few lines of 3_roomgen_output.h are cut of ?

they should look like this

```
	v.px += x;
	v.py += y;
	v.pz += z;
	if(v.px > room27.w-w) v.px=room27.w-w, v.vx*=0;
	if(v.py > room27.h-w) v.py=room27.h-w, v.vy*=-1;
	if(v.pz > room27.d-w) v.pz=room27.d-w, v.vz*=0;
	if(v.px < w-room27.w) v.px=w-room27.w, v.vx*=0;
	if(v.py < w-room27.h) v.py=w-room27.h, v.vy*=0;
	if(v.pz < w-room27.d) v.pz=w-room27.d, v.vz*=0;
	return v;
}
fn float room27_cast_down(View v, float d) {
	if(d < v.py + room27.h) return d;

	return v.py + room27.h;
}
```

also you could try running the script and the compile seperately, maybe there is an error that were not seeing

**Comment by PyMaster22** [comment]
I ran 3_less.c after adding those lines but when I tried compiling with clang it gave me this:
<pre>/usr/bin/ld: /tmp/3_less-8ed8ef.o: in function `open_gl&apos;:
3_less.c:(.text+0x78): undefined reference to `dlopen&apos;
/usr/bin/ld: 3_less.c:(.text+0xa6): undefined reference to `dlsym&apos;
/usr/bin/ld: /tmp/3_less-8ed8ef.o: in function `get_proc&apos;:
3_less.c:(.text+0x2c9): undefined reference to `dlsym&apos;
/usr/bin/ld: /tmp/3_less-8ed8ef.o: in function `main&apos;:
3_less.c:(.text+0x6157): undefined reference to `glfwInit&apos;
/usr/bin/ld: 3_less.c:(.text+0x617b): undefined reference to `glfwWindowHint&apos;
/usr/bin/ld: 3_less.c:(.text+0x6180): undefined reference to `glfwGetPrimaryMonitor&apos;
/usr/bin/ld: 3_less.c:(.text+0x618d): undefined reference to `glfwGetVideoMode&apos;
/usr/bin/ld: 3_less.c:(.text+0x61b6): undefined reference to `glfwCreateWindow&apos;
/usr/bin/ld: 3_less.c:(.text+0x61de): undefined reference to `glfwTerminate&apos;
/usr/bin/ld: 3_less.c:(.text+0x61f3): undefined reference to `glfwMakeContextCurrent&apos;
/usr/bin/ld: 3_less.c:(.text+0x61f9): undefined reference to `glfwGetProcAddress&apos;
/usr/bin/ld: 3_less.c:(.text+0x6239): undefined reference to `glfwTerminate&apos;
/usr/bin/ld: /tmp/3_less-8ed8ef.o: in function `loop&apos;:
3_less.c:(.text+0x626e): undefined reference to `glfwSetInputMode&apos;
/usr/bin/ld: 3_less.c:(.text+0x6468): undefined reference to `glfwGetTime&apos;
/usr/bin/ld: 3_less.c:(.text+0x6488): undefined reference to `glfwGetCursorPos&apos;
/usr/bin/ld: 3_less.c:(.text+0x64d1): undefined reference to `glfwSwapInterval&apos;
/usr/bin/ld: 3_less.c:(.text+0x64d6): undefined reference to `glfwRawMouseMotionSupported&apos;
/usr/bin/ld: 3_less.c:(.text+0x64f2): undefined reference to `glfwSetInputMode&apos;
/usr/bin/ld: 3_less.c:(.text+0x652d): undefined reference to `glfwWindowShouldClose&apos;
/usr/bin/ld: 3_less.c:(.text+0x6549): undefined reference to `glfwGetTime&apos;
/usr/bin/ld: 3_less.c:(.text+0x65bb): undefined reference to `sin&apos;
/usr/bin/ld: 3_less.c:(.text+0x65fa): undefined reference to `sin&apos;
/usr/bin/ld: 3_less.c:(.text+0x6658): undefined reference to `cos&apos;
/usr/bin/ld: 3_less.c:(.text+0x66aa): undefined reference to `cos&apos;
/usr/bin/ld: 3_less.c:(.text+0x66f6): undefined reference to `glfwPollEvents&apos;
/usr/bin/ld: 3_less.c:(.text+0x670d): undefined reference to `glfwGetCursorPos&apos;
/usr/bin/ld: 3_less.c:(.text+0x685c): undefined reference to `glfwGetKey&apos;
/usr/bin/ld: 3_less.c:(.text+0x68c0): undefined reference to `glfwGetKey&apos;
/usr/bin/ld: 3_less.c:(.text+0x68d4): undefined reference to `glfwGetKey&apos;
/usr/bin/ld: 3_less.c:(.text+0x68f0): undefined reference to `glfwGetKey&apos;
/usr/bin/ld: 3_less.c:(.text+0x6904): undefined reference to `glfwGetKey&apos;
/usr/bin/ld: /tmp/3_less-8ed8ef.o:3_less.c:(.text+0x6920): more undefined references to `glfwGetKey&apos; follow
/usr/bin/ld: /tmp/3_less-8ed8ef.o: in function `loop&apos;:
3_less.c:(.text+0x6950): undefined reference to `glfwGetMouseButton&apos;
/usr/bin/ld: 3_less.c:(.text+0x6964): undefined reference to `glfwGetKey&apos;
/usr/bin/ld: 3_less.c:(.text+0x69ba): undefined reference to `sqrt&apos;
/usr/bin/ld: 3_less.c:(.text+0x69ff): undefined reference to `cosf&apos;
/usr/bin/ld: 3_less.c:(.text+0x6a27): undefined reference to `sinf&apos;
/usr/bin/ld: 3_less.c:(.text+0x6a61): undefined reference to `sinf&apos;
/usr/bin/ld: 3_less.c:(.text+0x6a90): undefined reference to `cosf&apos;
/usr/bin/ld: 3_less.c:(.text+0x6e5f): undefined reference to `sqrtf&apos;
/usr/bin/ld: 3_less.c:(.text+0x7211): undefined reference to `cosf&apos;
/usr/bin/ld: 3_less.c:(.text+0x722e): undefined reference to `sinf&apos;
/usr/bin/ld: 3_less.c:(.text+0x7240): undefined reference to `sinf&apos;
/usr/bin/ld: 3_less.c:(.text+0x7255): undefined reference to `sinf&apos;
/usr/bin/ld: 3_less.c:(.text+0x7273): undefined reference to `cosf&apos;
/usr/bin/ld: 3_less.c:(.text+0x7285): undefined reference to `sinf&apos;
/usr/bin/ld: 3_less.c:(.text+0x729a): undefined reference to `cosf&apos;
/usr/bin/ld: 3_less.c:(.text+0x735a): undefined reference to `glfwGetWindowSize&apos;
/usr/bin/ld: 3_less.c:(.text+0x74be): undefined reference to `glfwSwapBuffers&apos;
/usr/bin/ld: /tmp/3_less-8ed8ef.o: in function `close_gl&apos;:
3_less.c:(.text+0x7500): undefined reference to `dlclose&apos;
clang: <font color="#EF2929"><b>error: </b></font>linker command failed with exit code 1 (use -v to see invocation)</pre>
So I tried with G++ but it gave me:
<pre><b>3_less.c:</b> In function ‘<b>char* shader_error_log(unsigned int)</b>’:
<b>3_less.c:175:20:</b> <font color="#EF2929"><b>error: </b></font>invalid conversion from ‘<b>void*</b>’ to ‘<b>char*</b>’ [<font color="#EF2929"><b>-fpermissive</b></font>]
  char *log = <font color="#EF2929"><b>malloc(length)</b></font>;
              <font color="#EF2929"><b>~~~~~~^~~~~~~~</b></font>
<b>3_less.c:</b> In function ‘<b>char* program_error_log(unsigned int)</b>’:
<b>3_less.c:185:20:</b> <font color="#EF2929"><b>error: </b></font>invalid conversion from ‘<b>void*</b>’ to ‘<b>char*</b>’ [<font color="#EF2929"><b>-fpermissive</b></font>]
  char *log = <font color="#EF2929"><b>malloc(length)</b></font>;
              <font color="#EF2929"><b>~~~~~~^~~~~~~~</b></font>
<b>3_less.c:</b> In function ‘<b>unsigned int create_shader(unsigned int, GLenum, char*)</b>’:
<b>3_less.c:195:23:</b> <font color="#EF2929"><b>error: </b></font>invalid conversion from ‘<b>void*</b>’ to ‘<b>const GLchar* const*</b>’ {aka ‘<b>const char* const*</b>’} [<font color="#EF2929"><b>-fpermissive</b></font>]
  glShaderSource(r, 1, <font color="#EF2929"><b>(void *)&amp;src</b></font>, 0);
                       <font color="#EF2929"><b>^~~~~~~~~~~~</b></font>
<b>3_less.c:</b> In function ‘<b>void loop(GLFWwindow*)</b>’:
<b>3_less.c:332:3:</b> <font color="#AD7FA8"><b>warning: </b></font>ISO C++ forbids converting a string constant to ‘<b>char*</b>’ [<font color="#AD7FA8"><b>-Wwrite-strings</b></font>]
  )<font color="#AD7FA8"><b>)</b></font>;
   <font color="#AD7FA8"><b>^</b></font>
<b>3_less.c:332:3:</b> <font color="#AD7FA8"><b>warning: </b></font>ISO C++ forbids converting a string constant to ‘<b>char*</b>’ [<font color="#AD7FA8"><b>-Wwrite-strings</b></font>]</pre>
I'm not a C, C++, C#, or Objective C developer so I don't know how to fix it.

**Comment by en-GB** [comment]
those are linker errors so basically missing or undeclared dependencies

for cos/sin/sqrt ... you need to add -lm to the command

for glfw* you need something like -lglfw3 or maybe its -lGLFW3 idk

make sure you have glfw installed, also i made a change so get the latest version

**Comment by PyMaster22** [comment]
Ok Thank you.
EDIT: glew3.h I fixed by adding it to the folder.

**Comment by PyMaster22** [comment]
I wasn't able to make it work.

**Comment by PyMaster22** [comment]
I decided to finally use WINE. I ran it on the .exe linked in your video but as always! It gave me another ERROR.
The error it gave is as follows:
<pre>Compiler error in shader 0
0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES
Compiler error in shader 1
0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES
Linker error in program
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader</pre>
If you know how to fix these with installations of packages or something I would be happy to.

**Comment by en-GB** [comment]
try with the newest version

**Comment by caussie** [comment]
@PyMaster22 `python3 3_roomgen.py && gcc -o 3_less 3_less.c -lglfw -lm -ldl` did it for me (if you're on debian/ubuntu/etc, you'll need to have `libglfw3-dev` installed)

**Comment by PyMaster22** [comment]
So. Many. ERRORS!
What I got from trying to compile the progam. AGIAN:
<pre><b>3_less.c:</b> In function ‘<b>loop</b>’:
<b>3_less.c:361:5:</b> <font color="#AD7FA8"><b>warning: </b></font>implicit declaration of function ‘<b>glfwRawMouseMotionSupported</b>’; did you mean ‘<b>glfwExtensionSupported</b>’? [<font color="#AD7FA8"><b>-Wimplicit-function-declaration</b></font>]
  if(<font color="#AD7FA8"><b>glfwRawMouseMotionSupported</b></font>())
     <font color="#AD7FA8"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
     <font color="#4E9A06">glfwExtensionSupported</font>
<b>3_less.c:362:28:</b> <font color="#EF2929"><b>error: </b></font>‘<b>GLFW_RAW_MOUSE_MOTION</b>’ undeclared (first use in this function); did you mean ‘<b>GLFW_MOUSE_BUTTON_8</b>’?
   glfwSetInputMode(window, <font color="#EF2929"><b>GLFW_RAW_MOUSE_MOTION</b></font>, GLFW_TRUE);
                            <font color="#EF2929"><b>^~~~~~~~~~~~~~~~~~~~~</b></font>
                            <font color="#4E9A06">GLFW_MOUSE_BUTTON_8</font>
<b>3_less.c:362:28:</b> <font color="#34E2E2"><b>note: </b></font>each undeclared identifier is reported only once for each function it appears in</pre>

**Comment by PyMaster22** [comment]
I also installed libglfw3-dev before I tried.

**Comment by caussie** [comment]
@PyMaster22 are you using ubuntu? if so, what version? raw mouse motion is a new feature in glfw 3.3, and bionic beaver only has glfw 3.2.1

**Comment by PyMaster22** [comment]
I'm using Linux Mint Debian Edition 4. I don't know If I should call it Ubuntu because 1) It has Debian Edition in the name 2) It's based off both.

**Comment by en-GB** [comment]
you can just delete lines 361 and 362

**Comment by PyMaster22** [comment]
On what file?

**Comment by PyMaster22** [comment]
Case closed everyone. We've done it (well not really me but you two did)!

I'm going to keep the issue open though :smile:
